### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by SMorettini** [tttapa/RPi-Cpp-Toolchain#2]
When I compile my package I have the following error. I understand that there is no Boost. How can I add Boost to the toolchain?
```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
Could NOT find Boost (missing: Boost_INCLUDE_DIR system)

```

**Comment by tttapa** [comment]
I haven't actually tried it, but it should be possible: 
https://www.boost.org/doc/libs/1_76_0/tools/build/doc/html/index.html#bbv2.tasks.crosscompile
