### ISSUE TITLE
What is this repository for??? 

### ISSUE THREAD

**Issue by EvgeniySavkin** [tttapa/RPi-Cpp-Toolchain#3]
What is this repository for??? I'm monitoring the Control_Surface repository. For what purposes can I use this code??

**Comment by tttapa** [comment]
This repository has build tools and scripts to cross-compile C++ applications for the Raspberry Pi, it's based on the scripts I used for a computer vision project using OpenCV on the Raspberry Pi and the Docker containers shared in our team to get reproducible builds across machines and operating systems.

It doesn't have anything to do with Control Surface, which is an Arduino library.
