### ISSUE TITLE
Complex build question

### ISSUE THREAD

**Issue by johncblacker** [tttapa/RPi-Cpp-Toolchain#4]
Suppose I want to build something like google's mediapipe which takes over 5 hours on the pi3.  This project has numerous dependencies - bazel, ffmpeg and opencv to name a few that have to be built first; then the build of mediapipe can take place.  If I understand your repo and doc, I'd have to install the dependencies from sources (a number of libav* libraries, for example), then I'd have to install/or build(tried this on the pi and ran into resources), following that I'd get the source for mediapipe and build it.  Am I on the right track here or am I misunderstanding the process?

**Comment by tttapa** [comment]
I'm not sure I understand what you're saying exactly.

The process explained in this repo and its documentation is to cross-compile all libraries and dependencies from source:
You have a folder on your computer that you install every library to. You need these libraries on your computer to build other libraries that depend on these libraries, and so on until you've built the entire dependency tree of the application or library you're interested in. When all that is done, you copy the libraries and other files that you have cross-compiled from your computer to the Pi you wish to use them on.

For large projects with dozens of nontrivial dependencies, building everything from source is not really feasible and you're much better off using a package manager, e.g. apt to install the dependencies. If the library (or version) you need is not in the repositories, you can build (cross-build) a limited number of packages from source.  
The approach using apt is explained here: https://tttapa.github.io/Pages/Raspberry-Pi/C++-Development-RPiOS/index.html

**Comment by johncblacker** [comment]
One thing I still haven't been clear on is: is the build taking place inside a docker container?  If so, where in the "directions" is the docker container started?  I'm looking at the "Building the C++ example project" and up to this point I don't see any command to start a docker image - am I missing something?

**Comment by tttapa** [comment]
The cross-compilation toolchain is built in a Docker container: 
https://github.com/tttapa/RPi-Cpp-Toolchain/blob/103eb26a24a7e03b9672638ece72881311a6c9df/toolchain/docker/merged/cross-toolchain/Dockerfile#L15
This Dockerfile is used to build an image here: 
https://github.com/tttapa/RPi-Cpp-Toolchain/blob/103eb26a24a7e03b9672638ece72881311a6c9df/toolchain/toolchain.sh#L142

The dependencies are cross-compiled in a Docker container:
https://github.com/tttapa/RPi-Cpp-Toolchain/blob/103eb26a24a7e03b9672638ece72881311a6c9df/toolchain/docker/merged/cross-build/Dockerfile#L51-L60
The Dockerfile is built here:
https://github.com/tttapa/RPi-Cpp-Toolchain/blob/103eb26a24a7e03b9672638ece72881311a6c9df/toolchain/toolchain.sh#L194

Then you copy the toolchain and the sysroot out of the Docker container:
https://github.com/tttapa/RPi-Cpp-Toolchain/blob/103eb26a24a7e03b9672638ece72881311a6c9df/toolchain/scripts/export.sh#L10-L26

Note that this is all handled by `toolchain.sh`, you don't have to do that manually:
https://github.com/tttapa/RPi-Cpp-Toolchain/blob/103eb26a24a7e03b9672638ece72881311a6c9df/toolchain/toolchain.sh#L215

And finally you build the example project natively, without Docker, using the toolchain and the sysroot you copied.

**Comment by johncblacker** [comment]
Yes, I understand now! Thank you.

----------------------------------------

Sep 30, 2021 11:11:14 AM Pieter P ***@***.***>:
