### ISSUE TITLE
./toolchain/toolchain.sh rpi3-armv8 --export fails due to certificate problems

### ISSUE THREAD

**Issue by martin-niklasson** [tttapa/RPi-Cpp-Toolchain#6]
Just following along on the documentation, I came to 
```
./toolchain/toolchain.sh rpi3-armv8 --export
```
This runs for a long time, but fails like this:
```
Step 59/98 : RUN chmod +x x264.sh && ./x264.sh
 ---> Running in fd4868d9aa60
+ git clone --single-branch --depth 1 https://code.videolan.org/videolan/x264.git
Cloning into 'x264'...
fatal: unable to access 'https://code.videolan.org/videolan/x264.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
The command '/bin/sh -c chmod +x x264.sh && ./x264.sh' returned a non-zero code: 128
```

As far as I can tell, this is a certificate problem inside the Docker container. Possibly related to this:
https://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c/69403278#69403278

**Comment by martin-niklasson** [comment]
I did this as a workaround to be able to continue:
```
git diff toolchain/docker/merged/cross-build/Dockerfile

 ENV RPI_SYSROOT="/home/develop/RPi-sysroot"
 ENV RPI_STAGING="/home/develop/RPi-staging"
 
+USER root
+RUN apt-get update && apt-get install --reinstall  ca-certificates -y
+RUN update-ca-certificates
+USER develop
+
 # Copy the cross-compilation toolchain
 COPY --from=cross-toolchain \
     "/home/develop/x-tools/${HOST_TRIPLE}" \

```

**Comment by tttapa** [comment]
This was because the images hadn't been built for some time, so the certificates were out of data. 
Everything has been updated now, but for future reference: you can get around this by `docker build`ing the base image again.
